site_name: Cryptography-Wiki
site_description: Cryptography-Wiki
site_author: Cryptography-Wiki Team
site_url: https://cryptography-wiki.org
repo_name: cryptography-wiki/cryptography-wiki
repo_url: https://github.com/cryptography-wiki/cryptography-wiki.github.io
edit_uri: blob/master/docs/
copyright: Copyright &copy; 2022 - 2022 Cryptography-Wiki Team
theme:
  name: material
  palette:
    primary: white
    accent: red
    scheme: preference
  language: zh
  features:
  - navigation.tabs
  - navigation.tabs.sticky
  - search.suggest
  - search.highlight
  - search.share
  font:
    text: Noto Sans
    code: Source Code Pro
plugins:
- search
- minify:
    minify_html: true
nav:
- 关于:
  - index.md
- 对称密码:
  - symmetric/introduction.md
- 非对称密码:
  - asymmetric/introduction.md
  - HNP:
    - Hidden Number Problems:
      - asymmetric/HNP/Hidden Number Problems/abstract.md
      - 第一章 介绍:
        - asymmetric/HNP/Hidden Number Problems/Chapter1/introduction.md
      - 第四章 比特安全:
        - asymmetric/HNP/Hidden Number Problems/Chapter4/introduction.md
        - asymmetric/HNP/Hidden Number Problems/Chapter4/4.1 Motivation.md
        - asymmetric/HNP/Hidden Number Problems/Chapter4/4.2 Framework.md
        - asymmetric/HNP/Hidden Number Problems/Chapter4/4.3 Diffie-Hellman and the Hidden Number Problem.md
        - asymmetric/HNP/Hidden Number Problems/Chapter4/4.4 Types of Partial Information.md
      - 第六章 选择乘数隐藏数问题:
        - asymmetric/HNP/Hidden Number Problems/Chapter6/introduction.md
        - asymmetric/HNP/Hidden Number Problems/Chapter6/6.1 Linear Operations.md
      - asymmetric/HNP/Hidden Number Problems/references.md
- 流密码:
  - stream/introduction.md
- 哈希函数:
  - hash/introduction.md
- 量子密码:
  - quantum/introduction.md
- 后量子密码:
  - post-quantum/introduction.md
- 侧信道安全:
  - side-channel/introduction.md
markdown_extensions:
- admonition
- md_in_html
- codehilite:
    guess_lang: false
- def_list
- footnotes
- meta
- toc:
    permalink: true
- pymdownx.arithmatex
- pymdownx.caret
- pymdownx.critic
- pymdownx.details
- pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji ''
    emoji_generator: !!python/name:materialx.emoji.to_svg ''
- pymdownx.highlight
- pymdownx.inlinehilite
- pymdownx.keys
- pymdownx.magiclink
- pymdownx.mark
- pymdownx.smartsymbols
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format ''
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.tilde
extra:
  copyright: CC BY-NC-SA 4.0
extra_javascript:
- https://cdnjs.loli.net/ajax/libs/pangu/3.3.0/pangu.min.js
- static/js/main.js
- https://cdnjs.loli.net/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML